### ISSUE TITLE
CUDA environment issues on Ampere GPUs

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#191]
The conda build of Torch is being built with a sufficiently high version of CUDA for some reason, and it's unable to work on newer Ampere GPUs. This primarily impacts the training project (and possibly the export project as well), and since we actually don't need the conda-dependent I/O libraries here (we just use hdf5), we can actually just install torch in poetry and ditch conda for training altogether. Something like this in `pyproject.toml` should work.

```toml
[tool.poetry.dependencies]
python = ">=3.8,<3.11"
"bbhnet.data" = {path = "../../../libs/data", develop  = true}
"bbhnet.trainer" = {path = "../../../libs/trainer", develop = true}
"bbhnet.logging" = {path = "../../../libs/logging", develop = true}

torch = {version = "^1.12", source = "torch"}

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu116"
secondary = true
default = false
```
It's worth thinking about standardizing an environment like this via containerization, something that contains
- `poetry`
- `torch`
- `ml4gw`
